### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#1]
Goal:
The start page should inform the user about the app and arouse interest. The site is intended to encourage the user to log in in order to be able to use the application.

## *** ! in this issue only page navigation is important !
Specific sign in and Log in functionalities will be covered in other issues ! ***

![Intro_Page_2022-04-26-1029](https://user-images.githubusercontent.com/100591318/165280083-72c8cb74-3cfb-4fd5-a840-760f75aa6b74.png)

## Acceptance criteria
- [ ] the page should have three button elements which are labeled according to their functionality (f.ex.: Log in with Google, Register/Sign up, Log in by Email)
- [ ] The page should be responsive (mobile first)
- [ ] "Log in by email" button should navigate the user to the Log in page
- [ ] "Log in with Google" should navigate the user to the Google Log in page (this criteria is connected to another issue dealing with Log In with Google)
- [ ] Register/Sign up button should navigate the user to the Register/Sign Up page
- [ ] The user can see the logo of the web application (if not created yet, placeholder)

## Tasks
- [ ] set up the client and server environment (connect Front with Backend)
- [ ] create a Log in with email button
- [ ] when the button is clicked the user should be navigated to the log in page
- [ ] create a Log in with google button
- [ ] create a sign up button
- [ ] navigate the user to the sign up page when clicked
- [ ] optional: create a button template with storybook
- [ ] add a Logo on the header section
- [ ] do unit/integration testing for the three buttons
- [ ] get code review
- [ ] final stage: design the page

## Size
small

**Comment by CJAkkuec** [comment]
**A general note for future reference:**
It makes perfect sense to want to start with a "title/login page", because in your app that's the first page you see. **But** - as a web developer, what we want to actually start with is the core feature of our app. Right now it wouldn't make sense to start with the "title/login page", because you can't meet your own acceptance criteria. You can't make any of the buttons do what they're supposed to, because there are no pages that you could route to.

Example:
Login with Email -> requires an existing backend to work (with sample data)
Login with Google -> requires Google Authentication
Register -> requires an existing backend and a "register page" with a working form, etc

All of these things I'd suggest are their own user stories.

I'd probably suggest that you think about what the core feature of your app is, and _start with that instead_. This user story is great (and definitely don't delete it :) ), but I'd recommend taking care of it during week 2, for example.

**Then, some feedback specific to this user story:**
Everything's looking pretty solid, although I'd argue that the size of this user story isn't small. In my opinion, it's at least medium, if not large - depending on whether you want your login buttons to do something, or if you're just setting up the design without any functionality. I'd recommend revisiting the estimated size of this user story once you've concluded working on it, so you get a better feel for the workload required.

I'd actually consider each login variation to be its own user story, because there's a lot going on during every login process.

That aside, I'm not entirely sure what you mean by "_set up the client and server environment (connect Front with Backend)_". It's a task, no doubt, but I'd say that's a general task, or its own user story.

**Highly recommended:** move this specific user story and its dependencies to week 2 or 3. If you've got any questions, definitely don't hesitate to ask. 

:) Great job otherwise! Looking forward to reading your other user stories!
