### ISSUE TITLE
Search the content

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#15]
## Value statement - a requirement, not a solution

As a user I want to search the content of my blog posts

## Description
![read_page-2022-04-28-0001(3)](https://user-images.githubusercontent.com/100591318/168550788-fe5dde05-d92e-49c8-8732-0f9020277e7c.png)

## Acceptance Criteria

- [ ] write words to search
- [ ] When the search button is clicked the posts which include the word in their title and text are displayed
- [ ] when clicking on the x button the posts are reset

## Task

- [ ] do research about image upload and integration in a data base
- [ ] create search bar with 2 buttons (search icon & cancel icon)
- [ ] add search function to display specific posts containing the word which is searched
- [ ] add reset functionality to reset

## Size
medium
