### ISSUE TITLE
timeline_function

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#16]
## Value statement - a requirement, not a solution

As a user I want to display the newest posts first.

## Description
![timeline_function-2022-04-28-0001](https://user-images.githubusercontent.com/100591318/168552922-c8699487-8cdd-44b9-99af-8bf2d22b5582.png)

## Acceptance Criteria

- [ ] toggle between descending/ascending order

## Task

- [ ] add ascending/descending order button
- [ ] add toggle functionality which includes ascending/descending function
- [ ] the name should be toggled in response to the displayed order

## Size
medium
