### ISSUE TITLE
Scroll up the page

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#17]
## Value statement - a requirement, not a solution

As a user I want to scroll up fast to reach the top of the page

## Description
![ScrollUp_function-2022-04-28-0001](https://user-images.githubusercontent.com/100591318/168554832-bdae594f-e0f4-45e3-af07-693a10e832ba.png)

## Acceptance Criteria

- [ ] clicking the scrollUp button brings the user to the top of the page
- [ ] appears at a specific distance to the top

## Task

- [ ] add scroll Up button
- [ ] toggle its appearance: when a certain distance is exceeded the button appears
- [ ] when scroll Up button is clicked the page is scrolled up smoothly to the top of the page.

## Size
small
