### ISSUE TITLE
Read and Create Page

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#2]
Goal: The user should be able to write a text which is displayed for reading

![read_create_page-2022-04-27-1207](https://user-images.githubusercontent.com/100591318/165502451-be2fff83-77f1-41a8-8c58-1f5b4ec68975.png)

## Acceptance Criteria

- [ ] starting at read page the user should be able to navigate to the create page by clicking the add icon/button
- [ ] on the creat epage the user can write a text
- [ ] by clicking the create/add button the user is directed back to the read page. Now the page should display the new post of the user.
- [ ] the user can add multiple posts

## Tasks

- [ ] create a read page which contains an add icon/button in the navbar
- [ ] when add button is clicked a new page is rendered
- [ ] the new page is the creat page. it contains a form element with a textfield and a (submit) button
- [ ] when the submit button is activated the read page is rendered and the new post appears on the page
- [ ] when the textfield is not used or empty, an alert will appear when the button is clicked to inform the user that the requirements for a new post are not fulfilled
- [ ] create a button/icon which closes the create page and disables editing
- [ ] Test the functionalities
- [ ] start designing and change labels (the names read and create page are just placeholders)

**Comment by CJAkkuec** [comment]
Strictly speaking, the create and read pages would be two separate user stories. I'd recommend starting with the read page and providing "fake data" as part of an initial state to map over - later on the data your create page/ your form would provide would replace this "fake data".

Your "fake data" could be an array of objects including key/value pairs (such as date: "01-01-2022", location: "Bahamas", etc). I'd suggest creating multiple such objects and trying to handle/display them with a map function.

I hope that provides you with a good starting point! Great job so far!
