### ISSUE TITLE
Edit/update posts

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#3]
## Goal
Users should be able to change their posts

![update_page-2022-04-27-1207](https://user-images.githubusercontent.com/100591318/165505347-1cd68572-cde7-43fb-9105-a187b34a93da.png)

## Acceptance criteria

- [ ] when the user clicks the edit button/icon the user is directed to the edit page
- [ ] edit page displays the existing text in a text field. The user can change the text.
- [ ] when the user clicks the update button the user is directed back to the read page which displays now the updated post.
- [ ] the user can close the edit page by clicking the close icon/button to cancel editing

## Tasks

- [ ] creat an edit icon/button on the read page
- [ ] when edit icon/button is activated a new page is rendered 
- [ ] create a form element with a textfield and a submit button. The current text is displayed in the textfield to allow editing.
- [ ] when update button is active (clicked) the read page is rendered displaying the updated post
- [ ] create close icon/button. When clicked the read page is rendered without the updated post
- [ ] test the functionality
- [ ] start desiging

**Comment by CJAkkuec** [comment]
This is a very good user story. I only have one minor note. : )

Under **Tasks**, the third task would be largely redundant. You don't need to create another form. The form you have on your create page can be used for this. You'd route the user toward the create form which you'd put into "edit mode", which isn't a literal mode but describing the concept of putting the data you already have into the form, etc. I don't want to spoil too much, just trying to spare you some grief ;).

**Comment by Sanae-G** [comment]
Thank you very much!
