### ISSUE TITLE
Delete post (read Page)

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#4]
## Goal
Users can delete posts

![delete_page-2022-04-27-1525](https://user-images.githubusercontent.com/100591318/165538087-0d15db16-f734-4497-8daf-2d73dcb39af2.png)

## Acceptance criterie

- [ ]  The user should be able to delete existing posts
- [ ] Before the post can be deleted, the user should confirm the request to avoid accidental deletion
- [ ] the read page refreshes without the (deleted) post

## Tasks

- [ ] create a delete button/icon
- [ ] when the delete button/icon is active an alert/popup appears asking the user to confirm the request
- [ ] when the user clicks yes (or something similar) the post is deleted
- [ ] when clicking cancel (f.ex. indicated by an X symbol) the post remains
- [ ] test functionality
- [ ] start designing

## Size
small

**Comment by mbosselmann** [comment]
Hi Sanae,

nice job! 👍 

I have some remarks and a question for you to consider:

Is there a reason why you don't separate your user story also in **value proposition** and **description**, because you just use **goal** here?

For your **value proposition** you could write:

**As a** user
**I need** to delete posts
**to be able to** remove posts that I no longer want to have

The reason is just a suggestion. There may be better reason that you have in your mind why a delete functionality is good. :)

Your image would be put under **Description**.

Your **tasks** section has tasks that are **acceptance criteria** for your feature:
- when the delete button/icon is active an alert/popup appears asking the user to confirm the request
- when the user clicks yes (or something similar) the post is deleted
- when clicking cancel (f.ex. indicated by an X symbol) the post remains

And: In your tasks you could also add storybook as task :)

As far as I understand you also want to create a delete modal. This should be added as task.
