### ISSUE TITLE
Store posts in backend using MongoDB

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#5]
## Value Proposition
As a user
I want to save my posts in a database
to be able to get access to my posts from anywhere

## Description
![CRUD_backend-2022-04-27-1547](https://user-images.githubusercontent.com/100591318/165540200-60ce4639-7d51-489b-8d5c-6df0357c79d9.png)

## Acceptance criteria

- [ ] the posts are stored in an external database (no local storage)
- [ ] the data can be fetched, changed and deleted using GET/POST/PUT or PATCH/DELETE requests
- [ ] When page reloads the current status should remain

## Tasks

- [ ] build the backend (install nodejs, express...)
- [ ] create a new database/collection in MongoDB Atlas
- [ ] connect backend with database (mongoose)
- [ ] make a GET request in the read page
- [ ] make a POST request in the create page
- [ ] make a PUT/PATCH request in the edit mode
- [ ] make a DELETE request tp delete posts
- [ ] testing

## Size
large

**Comment by mbosselmann** [comment]
And the next one. ;)

The same here for the **goal** instead of **value proposition** and **description** as mentioned in your other user story.

About your goal "When User refreshes or opens the application the current posts should be saved":
- I think you mean that the user opens the application existing posts should be loaded from the database but also new or updated posts should be in sync with the database or? 
I would also recommend to work with a Value proposition here. My suggestion:

**As a** user
**I want to** save my posts in a database
**to be able to** get access to my posts from anywhere

Just a suggestion. There may be a better reason. :)

I think that this user story is not **medium - large** but **large**.
