### ISSUE TITLE
read page

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#6]
## Goal

As a user i can read posts on the read page

![read_page-2022-04-28-0001](https://user-images.githubusercontent.com/100591318/165638835-648ce442-2a4f-4c71-a930-b2cd710c685a.png)

## Acceptance criteria

- [ ] display prewritten posts on the read page

## Tasks

- [ ] create an array with objects containing several posts
- [ ] fetch the json file and display them in the read page
- [ ] testing
- [ ] start designing

**Comment by CJAkkuec** [comment]
Good morning! 

Looking good - just a couple of minor notes:
"As a user i can read posts on the read page" -> I'd probably suggest the following phrasing: "As a user i want to read posts on the read page". : )

There's a couple more tasks you may want to include, such as "create a read page" ;).

And you forgot to add a size. (I'd suggest small - medium.)
