### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by Sanae-G** [Sanae-G/CapstoneProject#7]
## Value statement - a requirement, not a solution

As a user I want to upload an image to capture my travel memories

## Description

![upload_Image-2022-04-29-0912](https://user-images.githubusercontent.com/100591318/165921995-752b03e9-a721-42fa-b452-1fab89f8e4b2.png)

## Acceptance Criteria

- [ ] select image to upload (show file name in image bar)
- [ ] When the save button is clicked the image is stored in the database
- [ ] the image is displayed with the text as a post in the read page
- [ ] in edit mode the picture can be changed and updated
- [ ] the image size, file type and capacity should be limited

## Task

- [ ] do research about image upload and integration in a data base
- [ ] create upload image bar in create page/edit mode
- [ ] select image when upload button is active
- [ ] add POST/PUT/PATCH request when create or update button is active
- [ ] add GET request in read Page for image

## Size
Large
